Assignment2/Controllers/BillPayController.cs
using AssignmentClassLibrary;
using Assignment2.ViewModels;
using AssignmentClassLibrary.Data;
using AssignmentClassLibrary.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment2.Controllers;

public class BillPayController : Controller
{
    private readonly ModelDbContext _context;

    public BillPayController(ModelDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int id)
    {
        var payee = _context.Payee.ToList();
        var billpay = _context.BillPay.ToList();

        var viewModel = new BillPayViewModel
        {
            SelectedAccountNumber = id,
            Payees = payee,
            BillPays = billpay
        };
        return View(viewModel);
    }

    public async Task<IActionResult> CreateNewBillPay (BillPayViewModel viewModel)
    {
        var payee = await _context.Payee.FindAsync(viewModel.PayeeId);
        if (payee == null) ModelState.AddModelError(nameof(viewModel.PayeeId), "Payee does not exist.");
        if (viewModel.ScheduleTimeUtc < DateTime.UtcNow) ModelState.AddModelError(nameof(viewModel.ScheduleTimeUtc), "Cannot Set Date in the past");

        if (ModelState.IsValid)
        {
            _context.Add(new BillPay
            {
                AccountNumber = viewModel.SelectedAccountNumber,
                PayeeId = viewModel.PayeeId,
                Amount = viewModel.Amount,
                ScheduleTimeUtc = viewModel.ScheduleTimeUtc.ToUniversalTime(),
                Period = (Period) viewModel.Period
            });

            await _context.SaveChangesAsync();

            ModelState.Clear();

            return RedirectToAction("Index", "Customer");
        }

        return View("CreateBillPay", viewModel);

    }
    public async Task<IActionResult> CreateBillPay(BillPayViewModel viewModel)
    {
        return View(viewModel);
    }
    
    
    [HttpGet]
    public async Task<IActionResult> EditBillPay(int billPayId)
    {
        
        var billPay = await _context.BillPay.FindAsync(billPayId);

        var model = new BillPayViewModel
        {
            BillPayId = billPay.BillPayId,
            PayeeId = billPay.PayeeId,
            AccountNumber = billPay.AccountNumber,
            Amount = billPay.Amount,
            ScheduleTimeUtc = billPay.ScheduleTimeUtc.ToLocalTime(),
            Period = billPay.Period
        };

        return View("EditBillPay", model);
    }

    [HttpPost]
    public async Task<IActionResult> EditBillPay(BillPayViewModel model)
    {
        var billPay = await _context.BillPay.FindAsync(model.BillPayId);
        var destinationAccount = await _context.Account.FindAsync(model.AccountNumber);
        var payee = await _context.Payee.FindAsync(model.PayeeId);
        
        
        if (destinationAccount == null) ModelState.AddModelError(nameof(billPay.AccountNumber), "Account does not exist.");
        if (payee == null) ModelState.AddModelError(nameof(billPay.PayeeId), "Payee does not exist.");
        if (model.ScheduleTimeUtc < DateTime.UtcNow) ModelState.AddModelError(nameof(model.ScheduleTimeUtc), "Cannot Set Date in the past");


        if (ModelState.IsValid)
        {
            billPay.AccountNumber = model.AccountNumber;
            billPay.PayeeId = model.PayeeId;
            billPay.Amount = model.Amount;
            billPay.ScheduleTimeUtc = model.ScheduleTimeUtc.ToUniversalTime();
            billPay.Period = model.Period;

            await _context.SaveChangesAsync();
            Home();
        }

        return View("EditBillPay", model);
    }

    public async Task<RedirectToActionResult> CancelBillPay(int billPayId)
    {
        var billPay = await _context.BillPay.FindAsync(billPayId);

        _context.BillPay.Remove(billPay);

        await _context.SaveChangesAsync();
        
        return RedirectToAction("Index", "Customer");
    }
    public async Task<IActionResult> Home()
    {
        return RedirectToAction("Index", "Customer");
    }
}

Assignment2/Controllers/LoginController.cs
using AssignmentClassLibrary.Data;
using AssignmentClassLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using SimpleHashing;

namespace Assignment2.Controllers;

[Route("/User/SecureLogin")]
public class LoginController : Controller
{
    private readonly ModelDbContext _context;

    public LoginController(ModelDbContext context)
    {
        _context = context;
    }

    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(string loginID, string password)
    {
        var login = await _context.Login.FindAsync(loginID);
        // var customer = await _context.Customer.FindAsync(login.CustomerId);

        if (login == null || string.IsNullOrEmpty(password) || !PBKDF2.Verify(login.PasswordHash, password))
        {
            ModelState.AddModelError("LoginFailed", "Login failed, please try again.");
            return View(new Login {LoginId = loginID});
        }

        // Login customer.
        HttpContext.Session.SetInt32(nameof(Customer.CustomerId), login.CustomerId);
        HttpContext.Session.SetString(nameof(Customer.Name), login.Customer.Name);
        HttpContext.Session.SetString("loginId", loginID);

        return RedirectToAction("Index", "Customer");
    }

    [Route("LogoutNow")]
    public IActionResult Logout()
    {
        // Logout customer.
        HttpContext.Session.Clear();

        return RedirectToAction("Index", "Home");
    }
}

Assignment2/Views/Shared/_Layout.cshtml
@using AssignmentClassLibrary.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Assignment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Assignment2.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            @*<div class="brand">
                <img src="@Url.Content("/Images/Logo/MCBOA2.png")" alt="MCBOA"  asp-controller="Home" asp-action="Index">MCBA>
            </div>*@

            <div id="logo">
                <a alt="MCBOA" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content("/Images/Logo/MCBA-Logo.png")" width="50px" height="50px">
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav">
                    @{
                        var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerId)).HasValue;
                    }
                    @if (isLoggedIn)
                    {
                        var fullName = Context.Session.GetString(nameof(Customer.Name));

                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @fullName
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li>
                                        <a class="dropdown-item" asp-controller="MyProfile" asp-action="EditAccount">My Profile</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="ChangePassword" asp-action="EditPassword">Change Password</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav flex-grow-1">

                    @if (isLoggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="Index">My Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="BillPay" asp-action="Index">Bill Pay Payees</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">

    <div class="container">
        Copyright &copy; 2020 &mdash; Web Dev Assignmet 2
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>